$hyper = ALT_R

# Terminal
binds = $hyper, T, exec, $terminal start --cwd "$(sc terminal cwd)"

# Browser
bind = $hyper, B, exec, $browser
bind = $hyper SHIFT, B, exec, $browser --private-window

# Notes
bind = $hyper, O, exec, obsidian

# Password manager
bind = $hyper, P, exec, bitwarden-desktop
