$mod = SUPER
$hyper = ALT_R

# Copy/ Paste
bindd = $mod, C, Universal copy, sendshortcut, CTRL, Insert,
bindd = $mod, V, Universal paste, sendshortcut, SHIFT, Insert,
bindd = $mod, X, Universal cut, sendshortcut, CTRL, X,
bindd = $mod, X, Universal cut, sendshortcut, CTRL, X,
bindd = $mod, A, Select all, sendshortcut, CTRL, A,

# Clipboard history
binds = $hyper, SPACE, exec, walker -m clipboard
