### MOD3 = Left Physical Ctrl Key

# Close window
bind = SUPER, Q, killactive,

# Switch orientation 
bind = SUPER, slash, layoutmsg, togglesplit # dwindle

# Toggle floating
bind = SUPER SHIFT, F, togglefloating,

# Fullscreen
bindd = SUPER, RETURN, Fullscreen, fullscreen,

# Window focus 
bind = SUPER, H, movefocus, l
bind = SUPER, L, movefocus, r
bind = SUPER, K, movefocus, u
bind = SUPER, J, movefocus, d

# Move windows 
bind = SUPER SHIFT, H, movewindow, l
bind = SUPER SHIFT, L, movewindow, r
bind = SUPER SHIFT, K, movewindow, u
bind = SUPER SHIFT, J, movewindow, d

# Switch to workspaces 
bind = SUPER, 1, workspace, 1
bind = SUPER, 2, workspace, 2
bind = SUPER, 3, workspace, 3
bind = SUPER, 4, workspace, 4
bind = SUPER, 5, workspace, 5
bind = SUPER, 6, workspace, 6
bind = SUPER, 7, workspace, 7
bind = SUPER, 8, workspace, 8
bind = SUPER, 9, workspace, 9
bind = SUPER, 0, workspace, 10

# Move active window to a workspace
bind = SUPER SHIFT, 1, movetoworkspace, 1
bind = SUPER SHIFT, 2, movetoworkspace, 2
bind = SUPER SHIFT, 3, movetoworkspace, 3
bind = SUPER SHIFT, 4, movetoworkspace, 4
bind = SUPER SHIFT, 5, movetoworkspace, 5
bind = SUPER SHIFT, 6, movetoworkspace, 6
bind = SUPER SHIFT, 7, movetoworkspace, 7
bind = SUPER SHIFT, 8, movetoworkspace, 8
bind = SUPER SHIFT, 9, movetoworkspace, 9
bind = SUPER SHIFT, 0, movetoworkspace, 10

# Scroll through existing workspaces 
bind = SUPER, tab, workspace, e+1
bind = SUPER SHIFT, tab, workspace, e+1
bind = SUPER, mouse_down, workspace, e+1
bind = SUPER, mouse_up, workspace, e-1

# Move/resize windows with mainMod + LMB/RMB and dragging
bindm = SUPER, mouse:272, movewindow
bindm = SUPER, mouse:273, resizewindow

# Scroll through existing workspaces
bind = SUPER, mouse_down, workspace, e+1
bind = SUPER, mouse_up, workspace, e-1

# Resize active window
bindd = SUPER, code:20, Expand window left, resizeactive, -100 0    # - key
bindd = SUPER, code:21, Shrink window left, resizeactive, 100 0     # = key
bindd = SUPER SHIFT, code:20, Shrink window up, resizeactive, 0 -100
bindd = SUPER SHIFT, code:21, Expand window down, resizeactive, 0 1T, 

# Toggle groups
bindd = SUPER, period, Toggle window grouping, togglegroup
bindd = MOD3, period, Move active window out of group, moveoutofgroup

# Join groups
bindd = MOD3, H, Move window to group on left, moveintogroup, l
bindd = MOD3, L, Move window to group on right, moveintogroup, r
bindd = MOD3, K, Move window to group on top, moveintogroup, u
bindd = MOD3, J, Move window to group on bottom, moveintogroup, d

# Window navigation for grouped windows
bindd = MOD3, P, Move grouped window focus left, changegroupactive, b
bindd = MOD3, N, Move grouped window focus right, changegroupactive, f

