# Menus
binds = ALT_L, SPACE, exec, walker 
bind = ALT_L SHIFT, SPACE, exec, walker -m menus:quickmenu
bindd = ALT_L SHIFT, E, Emoji picker, exec, walker -m symbols 

# Controls
bindd = SUPER SHIFT, A, Audio control, exec, wezterm start --class tui-float -- wiremix -v output
bindd = SUPER SHIFT, B, Bluetooth control, exec, wezterm start --class tui-float -- bluetui
bindd = SUPER SHIFT, W, Wifi control, exec, wezterm start --class tui-float -- impala
bindd = SUPER SHIFT, T, Activity, exec, wezterm start --class btop-float -- btop 
