source = ~/.config/hypr/conf/keybinds/tiling.conf
source = ~/.config/hypr/conf/keybinds/clipboard.conf
source = ~/.config/hypr/conf/keybinds/media.conf
source = ~/.config/hypr/conf/keybinds/utils.conf
source = ~/.config/hypr/conf/keybinds/apps.conf

# Example special workspace (scratchpad)
bind = SUPER, S, togglespecialworkspace, magic
bind = SUPER SHIFT, S, movetoworkspace, special:magic

